services:
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:3002"
  #   environment:
  #     DATABASE_URL: "postgresql://postgres:postgres@db:5432/db_projeto"
  #   depends_on:
  #     - db
  #   command: npm run start:dev

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_projeto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
